sudo: required
services:
  - docker

before install:
  - docker build -t awscpukiller/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run awscpukiller/react-test npm test --  --coverage

after_success:
  - docker build -t awscpukiller/multi-client ./client
  - docker build -t awscpukiller/multi-nginx ./nginx
  - docker build -t awscpukiller/multi-server ./server
  - docker build -t awscpukiller/multi-worker ./worker
  # Log in to the docker CLI "Docker Login"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push awscpukiller/multi-client
  - docker push awscpukiller/multi-nginx
  - docker push awscpukiller/multi-server
  - docker push awscpukiller/multi-worker